# Site settings
title: Can Xie(谢灿)
email: xiecan02@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a junior undergraduate from the School of Computer Science and Technology, Shandong University.
  I study machine learning, nlp, and multimedia information computing.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://github.com/xvolcano02" # the base hostname & protocol for your site
github_username:  xvolcano02
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
